#!/bin/sh
set -e

echo "Post-Installation Macro"

IS_UPGRADE=false

case "$1" in
	configure)
		# Set user permissions
		mkdir -p /opt/geld/webapps/twitter-github-mashup-api
        chown root:root /etc/systemd/system/twitter-github-mashup-api.service
        chmod  644 /etc/systemd/system/twitter-github-mashup-api.service
		chown -R root:www-data /opt/geld/webapps/twitter-github-mashup-api
		chown -R root:www-data /opt/geld/webapps/twitter-github-mashup-api
		find /opt/geld/webapps/twitter-github-mashup-api -type d -print0 | xargs -0 chmod 755
		find /opt/geld/webapps/twitter-github-mashup-api -type f -print0 | xargs -0 chmod 644
		chmod 775 /opt/geld/webapps/twitter-github-mashup-api/static/data
		chmod 755 /opt/geld/webapps/twitter-github-mashup-api/generate_data.py
		
		# If $1=configure and $2 is set, this is an upgrade
		if [ "$2" != "" ]; then
			IS_UPGRADE=true
		fi
		if [ "$IS_UPGRADE" = "true" ]; then
			echo -n "Restarting service..."
			systemctl daemon-reload
			systemctl restart twitter-github-mashup-api || true
			echo " OK"
			echo -n "Reloading nginx service..."
			sudo service nginx reload
			echo " OK"
		else
			echo -n "Starting service..."
			systemctl daemon-reload
			systemctl enable twitter-github-mashup-api || true
			systemctl start twitter-github-mashup-api || true
			echo " OK"
			echo -n "Reloading nginx service..."
			sudo service nginx reload
			echo " OK"
		fi
		;;
esac
